
    - name: Add java 8 ppa
      apt_repository: repo="ppa:openjdk-r/ppa" update_cache=yes
      tags:
      - tomcat
      - development
      sudo: yes

    - name: Install java
      apt: pkg=openjdk-8-jre
      tags:
      - tomcat
      - development
      sudo: yes

    - name: Install tomcat
      apt: pkg=tomcat7
      sudo: yes
      tags:
      - tomcat
      - run

    - name: Install tomcat native
      apt: pkg=libtcnative-1
      sudo: yes
      tags:
      - tomcat
      - run

    - name: Install tomcat7-admin
      apt: pkg=tomcat7-admin
      sudo: yes
      tags:
      - tomcat
      - manage
      notify:
      - Setup tomcat users
      - Setup tomcat defaults
      - Restart tomcat
