
    - name: Install tomcat
      apt: pkg=tomcat7
      sudo: yes
      tags:
      - tomcat
      - run
      notify:
      - Setup tomcat defaults

    - name: Install tomcat native
      apt: pkg=libtcnative-1
      sudo: yes
      tags:
      - tomcat
      - run

    - name: Install tomcat7-admin
      apt: pkg=tomcat7-admin
      sudo: yes
      tags:
      - tomcat
      - manage
      notify:
      - Setup tomcat users
